### ISSUE TITLE
Is there any chance this could be updated to be Django 2.x

### ISSUE THREAD

**Issue by csev** [edcrewe/django-cookieless#3]
I a one of those rare folks that need this feature (coming from PHP to Django) because my applications must function within iframes and have a different session for each tab.  I would pay some money to have this updated to 2.x if you were interested.

**Comment by edcrewe** [comment]
Hi Charles,

Glad to hear somebody wants one of my old open source contributions :-)

I will take a look at whats involved - and if it will take much work to upgrade it and let you know.

Thanks,
Ed

**Comment by csev** [comment]
I have also built a few features on top of the PHP cookiless sessions that make them far more secure at scale.  It looks like you might have some of those features already - but if you can get it to 2.x, I can look the code over and maybe make some suggestions for security improvements (all optional and controlled in settings.py of course).

**Comment by csev** [comment]
Did you do it or is it still in progress?   I am happy to be your first tester and then propose some changes / improvements after I find my way around.

**Comment by edcrewe** [comment]
Hi Charles,

I did a little work on this ... just started to get it going with current
Django.

I need to do some more to finish it off and package it up as a new
release.  I just havent got time right now.

You can try using the checkout from master and see if it works for you yet
if you like.

I will hopefully finish it off in the next week or so.

Thanks,
Ed

**Comment by edcrewe** [comment]
Hi Charles,

OK I have released a new version 1.1 for Django 2.2 and Python 3

See https://pypi.org/project/django-cookieless/

Please try it out and let me know if there are any issues.

Thanks,
Ed Crewe

**Comment by csev** [comment]
Thanks - we will test this asap and get you some feedback and maybe PRs.  Can I send you something?  Are you part of github sponsors?

**Comment by edcrewe** [comment]
Hi Charles,

Ok sure I will look out for any PRs. I have signed up to github sponsors,
and am on the waiting list.

Thanks
